name: Python application

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Set up FFMpeg
      uses: FedericoCarboni/setup-ffmpeg@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check for changes in input.txt
      id: checkfile
      run: |
        echo "::set-output name=changed::$(git diff --name-only HEAD^ HEAD | grep '^examples/input.txt$' || echo 'false')"
    - name: Run application
      # if: steps.checkfile.outputs.changed != 'false'
      run: |
        export URL=$( cat examples/input.txt ) && echo ${URL} && URL=${URL} make sub
        if [ -f examples/result.txt ]; then
          echo examples/result.txt
        fi
